info:
  namespace: supreme
items:
  # Components
  supreme_attribute_bomb:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201573
      model_path: "components/supreme_attribute_bomb"
  supreme_attribute_fortune:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201574
      model_path: "components/supreme_attribute_fortune"
  supreme_attribute_impetus:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201575
      model_path: "components/supreme_attribute_impetus"
  supreme_attribute_magic:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201572
      model_path: "components/supreme_attribute_magic"
  supreme_blend_machine:
    display_name: supreme
    permission: supreme
    resource:
      material: BUBBLE_CORAL_BLOCK
      generate: false
      model_id: 2201560
      model_path: "components/supreme_blend_machine"
  supreme_carriage_machine:
    display_name: supreme
    permission: supreme
    resource:
      material: DEAD_HORN_CORAL_BLOCK
      generate: false
      model_id: 2201556
      model_path: "components/supreme_carriage_machine"
  supreme_cetrus_aqua:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201570
      model_path: "components/supreme_cetrus_aqua"
  supreme_cetrus_ignis:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201571
      model_path: "components/supreme_cetrus_ignis"
  supreme_cetrus_lumium:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201567
      model_path: "components/supreme_cetrus_lumium"
  supreme_cetrus_lux:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201568
      model_path: "components/supreme_cetrus_lux"
  supreme_cetrus_ventus:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201569
      model_path: "components/supreme_cetrus_ventus"
  supreme_conveyance_machine:
    display_name: supreme
    permission: supreme
    resource:
      material: HORN_CORAL_BLOCK
      generate: false
      model_id: 2201557
      model_path: "components/supreme_conveyance_machine"
  supreme_core_of_alloy:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201566
      model_path: "components/supreme_core_of_alloy"
  supreme_core_of_block:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201561
      model_path: "components/supreme_core_of_block"
  supreme_core_of_color:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201564
      model_path: "components/supreme_core_of_color"
  supreme_core_of_death:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201562
      model_path: "components/supreme_core_of_death"
  supreme_core_of_life:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201563
      model_path: "components/supreme_core_of_life"
  supreme_core_of_nature:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201565
      model_path: "components/supreme_core_of_nature"
  supreme_crystallizer_machine:
    display_name: supreme
    permission: supreme
    resource:
      material: TUBE_CORAL_BLOCK
      generate: false
      model_id: 2201559
      model_path: "components/supreme_crystallizer_machine"
  supreme_inductive_machine:
    display_name: supreme
    permission: supreme
    resource:
      material: DEAD_FIRE_CORAL_BLOCK
      generate: false
      model_id: 2201552
      model_path: "components/supreme_inductive_machine"
  supreme_inductor_machine:
    display_name: supreme
    permission: supreme
    resource:
      material: FIRE_CORAL_BLOCK
      generate: false
      model_id: 2201553
      model_path: "components/supreme_inductor_machine"
  supreme_petrifier_machine:
    display_name: supreme
    permission: supreme
    resource:
      material: DEAD_TUBE_CORAL_BLOCK
      generate: false
      model_id: 2201558
      model_path: "components/supreme_petrifier_machine"
  supreme_rustless_machine:
    display_name: supreme
    permission: supreme
    resource:
      material: DEAD_BRAIN_CORAL_BLOCK
      generate: false
      model_id: 2201554
      model_path: "components/supreme_rustless_machine"
  supreme_stainless_machine:
    display_name: supreme
    permission: supreme
    resource:
      material: BRAIN_CORAL_BLOCK
      generate: false
      model_id: 2201555
      model_path: "components/supreme_stainless_machine"
  supreme_supreme:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201551
      model_path: "components/supreme_supreme"
  supreme_supreme_nugget:
    display_name: supreme
    permission: supreme
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2201550
      model_path: "components/supreme_supreme_nugget"
  # Waepons
  supreme_axe:
    display_name: supreme
    permission: supreme
    resource:
      material: NETHERITE_AXE
      generate: false
      model_id: 2201915
      model_path: "weapons/supreme_axe"
  # supreme_hoe:
  #   display_name: supreme
  #   permission: supreme
  #   resource:
  #     material: NETHERITE_HOE
  #     generate: false
  #     model_id: None
  #     model_path: "weapons/supreme_hoe"
  supreme_pickaxe:
    display_name: supreme
    permission: supreme
    resource:
      material: NETHERITE_PICKAXE
      generate: false
      model_id: 2201924
      model_path: "weapons/supreme_pickaxe"
  supreme_shovel:
    display_name: supreme
    permission: supreme
    resource:
      material: NETHERITE_SHOVEL
      generate: false
      model_id: 2201933
      model_path: "weapons/supreme_shovel"
  supreme_sword:
    display_name: supreme
    permission: supreme
    resource:
      material: NETHERITE_SWORD
      generate: false
      model_id: 2201900
      model_path: "weapons/supreme_sword"
  # Armor
  supreme_supreme_helmet:
    display_name: supreme
    permission: supreme
    resource:
      material: NETHERITE_HELMET
      generate: false
      model_id: 2201945
      model_path: "armor/helmet/supreme_supreme_helmet"
  supreme_supreme_chestplate:
    display_name: supreme
    permission: supreme
    resource:
      material: NETHERITE_CHESTPLATE
      generate: false
      model_id: 2201954
      model_path: "armor/chestplate/supreme_supreme_chestplate"
  supreme_supreme_leggings:
    display_name: supreme
    permission: supreme
    resource:
      material: NETHERITE_LEGGINGS
      generate: false
      model_id: 2201963
      model_path: "armor/leggings/supreme_supreme_leggings"
  supreme_supreme_boots:
    display_name: supreme
    permission: supreme
    resource:
      material: NETHERITE_BOOTS
      generate: false
      model_id: 2201972
      model_path: "armor/boots/supreme_supreme_boots"
