info:
  namespace: litexpansion
items:
  advanced_alloy:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: PAPER
      generate: false
      model_id: 2200810
      model_path: "materials/advanced_alloy"
  advanced_circuit:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: COBWEB
      generate: false
      model_id: 2200811
      model_path: "materials/advanced_circuit"
  coal_dust:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: BLACK_DYE
      generate: false
      model_id: 2200812
      model_path: "materials/coal_dust"
  copper_cable:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: STRING
      generate: false
      model_id: 2200813
      model_path: "materials/copper_cable"
  electronic_circuit:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: COBWEB
      generate: false
      model_id: 2200814
      model_path: "materials/electronic_circuit"
  iridium:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: WHITE_DYE
      generate: false
      model_id: 2200815
      model_path: "materials/iridium"
  iridium_plate:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: PAPER
      generate: false
      model_id: 2200816
      model_path: "materials/iridium_plate"
  mag-thor:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: IRON_INGOT
      generate: false
      model_id: 2200817
      model_path: "materials/mag-thor"
  mixed_metal_ingot:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: IRON_INGOT
      generate: false
      model_id: 2200818
      model_path: "materials/mixed_metal_ingot"
  raw_carbon_fibre:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: BLACK_DYE
      generate: false
      model_id: 2200819
      model_path: "materials/raw_carbon_fibre"
  raw_carbon_mesh:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: BLACK_DYE
      generate: false
      model_id: 2200820
      model_path: "materials/raw_carbon_mesh"
  refined_iron:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: IRON_INGOT
      generate: false
      model_id: 2200821
      model_path: "materials/refined_iron"
  scrap:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: DEAD_BUSH
      generate: false
      model_id: 2200822
      model_path: "materials/scrap"
  thorium:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: PLAYER_HEAD
      generate: false
      model_id: 2200823
      model_path: "materials/thorium"
  uninsulated_copper_cable:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: STRING
      generate: false
      model_id: 2200824
      model_path: "materials/uninsulated_copper_cable"
  uu_matter:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: PURPLE_DYE
      generate: false
      model_id: 2200825
      model_path: "materials/uu_matter"
  cargo_configurator:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: COMPASS
      generate: false
      model_id: 2200826
      model_path: "tools/cargo_configurator"
  nano_blade:
    display_name: litexpansion
    permission: litexpansion
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_id: 2200827
      model_path: "tools/nano_blade"
