info:
  namespace: extra_gear
items:
  aluminum_boots:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_BOOTS
      generate: false
      model_id: 2201201
      model_path: "armor/aluminum/aluminum_boots"
  aluminum_chestplate:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_CHESTPLATE
      generate: false
      model_id: 2201202
      model_path: "armor/aluminum/aluminum_chestplate"
  aluminum_helmet:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_HELMET
      generate: false
      model_id: 2201203
      model_path: "armor/aluminum/aluminum_helmet"
  aluminum_leggings:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_LEGGINGS
      generate: false
      model_id: 2201204
      model_path: "armor/aluminum/aluminum_leggings"
  cobalt_boots:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_BOOTS
      generate: false
      model_id: 2201205
      model_path: "armor/cobalt/cobalt_boots"
  cobalt_chestplate:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_CHESTPLATE
      generate: false
      model_id: 2201206
      model_path: "armor/cobalt/cobalt_chestplate"
  cobalt_helmet:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_HELMET
      generate: false
      model_id: 2201207
      model_path: "armor/cobalt/cobalt_helmet"
  cobalt_leggings:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_LEGGINGS
      generate: false
      model_id: 2201208
      model_path: "armor/cobalt/cobalt_leggings"
  copper_boots:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: LEATHER_BOOTS
      generate: false
      model_id: 2201209
      model_path: "armor/copper/copper_boots"
  copper_chestplate:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: LEATHER_CHESTPLATE
      generate: false
      model_id: 2201210
      model_path: "armor/copper/copper_chestplate"
  copper_helmet:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: LEATHER_HELMET
      generate: false
      model_id: 2201211
      model_path: "armor/copper/copper_helmet"
  copper_leggings:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: LEATHER_LEGGINGS
      generate: false
      model_id: 2201212
      model_path: "armor/copper/copper_leggings"
  lead_boots:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_BOOTS
      generate: false
      model_id: 2201213
      model_path: "armor/lead/lead_boots"
  lead_chestplate:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_CHESTPLATE
      generate: false
      model_id: 2201214
      model_path: "armor/lead/lead_chestplate"
  lead_helmet:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_HELMET
      generate: false
      model_id: 2201215
      model_path: "armor/lead/lead_helmet"
  lead_leggings:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_LEGGINGS
      generate: false
      model_id: 2201216
      model_path: "armor/lead/lead_leggings"
  magnesium_boots:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_BOOTS
      generate: false
      model_id: 2201217
      model_path: "armor/magnesium/magnesium_boots"
  magnesium_chestplate:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_CHESTPLATE
      generate: false
      model_id: 2201218
      model_path: "armor/magnesium/magnesium_chestplate"
  magnesium_helmet:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_HELMET
      generate: false
      model_id: 2201219
      model_path: "armor/magnesium/magnesium_helmet"
  magnesium_leggings:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_LEGGINGS
      generate: false
      model_id: 2201220
      model_path: "armor/magnesium/magnesium_leggings"
  silver_boots:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_BOOTS
      generate: false
      model_id: 2201221
      model_path: "armor/silver/silver_boots"
  silver_chestplate:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_CHESTPLATE
      generate: false
      model_id: 2201222
      model_path: "armor/silver/silver_chestplate"
  silver_helmet:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_HELMET
      generate: false
      model_id: 2201223
      model_path: "armor/silver/silver_helmet"
  silver_leggings:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_LEGGINGS
      generate: false
      model_id: 2201224
      model_path: "armor/silver/silver_leggings"
  steel_boots:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_BOOTS
      generate: false
      model_id: 2201225
      model_path: "armor/steel/steel_boots"
  steel_chestplate:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_CHESTPLATE
      generate: false
      model_id: 2201226
      model_path: "armor/steel/steel_chestplate"
  steel_helmet:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_HELMET
      generate: false
      model_id: 2201227
      model_path: "armor/steel/steel_helmet"
  steel_leggings:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_LEGGINGS
      generate: false
      model_id: 2201228
      model_path: "armor/steel/steel_leggings"
  tin_boots:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_BOOTS
      generate: false
      model_id: 2201229
      model_path: "armor/tin/tin_boots"
  tin_chestplate:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_CHESTPLATE
      generate: false
      model_id: 2201230
      model_path: "armor/tin/tin_chestplate"
  tin_helmet:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_HELMET
      generate: false
      model_id: 2201231
      model_path: "armor/tin/tin_helmet"
  tin_leggings:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_LEGGINGS
      generate: false
      model_id: 2201232
      model_path: "armor/tin/tin_leggings"
  zinc_boots:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_BOOTS
      generate: false
      model_id: 2201233
      model_path: "armor/zinc/zinc_boots"
  zinc_chestplate:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_CHESTPLATE
      generate: false
      model_id: 2201234
      model_path: "armor/zinc/zinc_chestplate"
  zinc_helmet:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_HELMET
      generate: false
      model_id: 2201235
      model_path: "armor/zinc/zinc_helmet"
  zinc_leggings:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_LEGGINGS
      generate: false
      model_id: 2201236
      model_path: "armor/zinc/zinc_leggings"
  aluminum_brass_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201237
      model_path: "swords/aluminum_brass_sword"
  aluminum_bronze_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201238
      model_path: "swords/aluminum_bronze_sword"
  aluminum_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201239
      model_path: "swords/aluminum_sword"
  billon_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201240
      model_path: "swords/billon_sword"
  brass_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201241
      model_path: "swords/brass_sword"
  bronze_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201242
      model_path: "swords/bronze_sword"
  cobalt_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201243
      model_path: "swords/cobalt_sword"
  copper_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201244
      model_path: "swords/copper_sword"
  corinthian_bronze_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201245
      model_path: "swords/corinthian_bronze_sword"
  damascus_steel_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201246
      model_path: "swords/damascus_steel_sword"
  duralumin_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201247
      model_path: "swords/duralumin_sword"
  ferrosilicon_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201248
      model_path: "swords/ferrosilicon_sword"
  gilded_iron_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: GOLDEN_SWORD
      generate: false
      model_id: 2201249
      model_path: "swords/gilded_iron_sword"
  hardened_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201250
      model_path: "swords/hardened_sword"
  lead_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201251
      model_path: "swords/lead_sword"
  magnesium_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201252
      model_path: "swords/magnesium_sword"
  nickel_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201253
      model_path: "swords/nickel_sword"
  reinforced_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201254
      model_path: "swords/reinforced_sword"
  silver_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201255
      model_path: "swords/silver_sword"
  solder_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201256
      model_path: "swords/solder_sword"
  steel_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201257
      model_path: "swords/steel_sword"
  tin_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201258
      model_path: "swords/tin_sword"
  zinc_sword:
    display_name: extra_gear
    permission: extra_gear
    resource:
      material: IRON_SWORD
      generate: false
      model_id: 2201259
      model_path: "swords/zinc_sword"
